name: Review Dog
on: [pull_request]
jobs:
  eslint:
    name: Sniffing code
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
