# # This is a basic workflow that is manually triggered

# name: Manual workflow

# # Controls when the action will run. Workflow runs when manually triggered using the UI
# # or API.
# on: [pull_request]
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel

name: Test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install reviewdog (default)
        uses: ./
      - run: reviewdog -version

      - name: install reviewdog (nightly)
        uses: ./
        with:
          reviewdog_version: nightly
      - run: reviewdog -version | grep nightly

      - name: install reviewdog (with reviewdog_version)
        uses: ./
        with:
          reviewdog_version: v0.17.4
      - run: test "$(reviewdog -version)" = '0.17.4'

  container:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: install reviewdog
        uses: ./
      - run: reviewdog -version


# jobs:
#   # This workflow contains a single job called "greet"
#   greet:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Runs a single command using the runners shell
#     - name: Send greeting
#       run: echo "Hello ${{ inputs.name }}"
      
#     - uses: reviewdog/action-setup@v1
#     - run: reviewdog -version
#     - name: Check out code.
#       uses: actions/checkout@v1
        
#     - name: misspell
#       uses: reviewdog/action-misspell@v1
#       with:
#         github_token: ${{ secrets.github_token }}
    
#     - name: Run reviewdog
#       env:
#         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         golint ./... | reviewdog -f=golint -reporter=github-pr-check
