# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  golangci-lint:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - name: Setup reviewdog
      run: |
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
        echo ::add-path::$HOME/bin
        name: runner / golangci-lint
        runs-on: ubuntu-latest
        steps:
          - name: Check out code into the Go module directory
            uses: actions/checkout@v1
          - name: golangci-lint
            uses: reviewdog/action-golangci-lint@v1
            with:
              github_token: ${{ secrets.github_token }}
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
    - name: misspell
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.github_token }}
    
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        golint ./... | reviewdog -f=golint -reporter=github-pr-check
